--- #YAML:1.0
name:                Wx-Perl-ProcessStream
version:             0.23
abstract:            access IO of external processes via events
license:             ~
author:              
    - Mark Dootson <mdootson@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Time::HiRes:                   1.2
    Wx:                            0.5
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
