# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Wx-Perl-ProcessStream
version:      0.08
version_from: lib/Wx/Perl/ProcessStream.pm
installdirs:  site
requires:
    Wx:                            0.5

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
